declare namespace App.Data {
export type CarrierData = {
id: number | null;
tracking_id: string | null;
forwarder: string | null;
carrier: string | null;
expected_delivery_date: string | null;
shipped_at: string | null;
delivered_at: string | null;
tracking_order_id: number | null;
};
export type CategoryData = {
id: number | null;
name: string | null;
description: string | null;
};
export type CountryData = {
country: string | null;
dial_code: number | null;
country_code: string | null;
};
export type CrossReferenceData = {
id: number | null;
product_id: number | null;
cross_reference_id: string | null;
tecdoc_article: App.Data.TecdocArticleData | null;
created_at: string | null;
updated_at: string | null;
};
export type CustomerData = {
id: number | null;
name: string | null;
email: string | null;
phone: string | null;
company_name: string | null;
tax_id: string | null;
address: string | null;
city: string | null;
state: string | null;
country: string | null;
postal_code: string | null;
user_id: number | null;
created_at: string | null;
updated_at: string | null;
internal_orders: Array<any> | null;
};
export type FileData = {
id: number | null;
fileable_id: number | null;
fileable_type: string | null;
file_location: string | null;
file_url: string | null;
collection: string | null;
file_name: string | null;
created_at: string | null;
updated_at: string | null;
};
export type InboundOrderData = {
id: number | null;
order_number: string | null;
supplier_name: string | null;
supplier_invoice_no: string | null;
supplier_code: string | null;
document_type: string | null;
invoice_date: string | null;
payment_method: string | null;
bank_account: string | null;
currency: string | null;
total_amount: number | null;
tax_amount: number | null;
notes: string | null;
supplier_tax_id: string | null;
supplier_address: string | null;
due_date: string | null;
expected_date: string | null;
verified: boolean | null;
status: string | null;
items_count: number | null;
items: Array<App.Data.OrderItemData> | null;
created_by: number | null;
updated_by: number | null;
order_date: string | null;
created_at: string | null;
updated_at: string | null;
};
export type InternalOrderData = {
id: number | null;
order_number: string | null;
branch_id: number | null;
delivery_type: string | null;
customer_id: number | null;
customer_name: string | null;
status: string | null;
warehouse_comment: string | null;
created_by: number | null;
confirmed_by: number | null;
items: Array<App.Data.InternalOrderItemData> | null;
ship_orders: Array<App.Data.ShipOrderData> | null;
created_at: string | null;
updated_at: string | null;
customer: App.Data.CustomerData | null;
};
export type InternalOrderItemData = {
id: number | null;
product_name: string | null;
catalog_number: string | null;
quantity: number | null;
received_quantity: number | null;
confirmed_quantity: number | null;
correction_quantity: number | null;
undelivered_quantity: number | null;
status: string | null;
unit: string | null;
comments: string | null;
customer_name: string | null;
created_at: string | null;
updated_at: string | null;
history: Array<App.Data.InternalOrderItemHistoryData> | null;
created_by: number | null;
created_by_name: string | null;
};
export type InternalOrderItemHistoryData = {
id: number | null;
internal_order_item_id: number | null;
order_number: string | null;
product_name: string | null;
quantity: number | null;
status: string | null;
message: string | null;
action_by: number | null;
action_by_name: string | null;
created_at: string | null;
updated_at: string | null;
};
export type OemReferenceData = {
id: number | null;
product_id: number | null;
oem_brand: string | null;
oem_display_no: string | null;
oem_article_no: string | null;
created_at: string | null;
updated_at: string | null;
};
export type OrderItemData = {
id: number | null;
inbound_order_id: number | null;
product_id: number | null;
unique_id: string | null;
sku: string | null;
category: string | null;
brand: string | null;
item_name: string | null;
barcode: string | null;
supplies_barcode: string | null;
rfid_barcode: string | null;
qty: number | null;
received_qty: number | null;
unit: string | null;
purchase_price: number | null;
rebate: number | null;
markup: number | null;
tax: number | null;
status: string | null;
sales_price: number | null;
max_discount: number | null;
kpd_code: string | null;
net_purchase_price: number | null;
total_price: number | null;
received_at: string | null;
created_at: string | null;
updated_at: string | null;
};
export type OutboundOrderData = {
id: number | null;
order_number: string | null;
customer_id: number | null;
customer_name: string | null;
status: string | null;
items_count: number | null;
vehicle: string | null;
notes: string | null;
order_date: string | null;
employer_id: number | null;
employer: Array<App.Data.UserData> | null;
customer: Array<App.Data.CustomerData> | null;
items: Array<App.Data.OutboundOrderItemData> | null;
created_by: number | null;
updated_by: number | null;
created_at: string | null;
updated_at: string | null;
};
export type OutboundOrderItemData = {
id: number | null;
product_id: number | null;
product_name: string | null;
product_brand: string | null;
product_sku: string | null;
qty: number | null;
barcode: string | null;
shipped_qty: number | null;
available_qty: number | null;
price: number | null;
status: string | null;
warehouse_locations: string | null;
};
export type PermissionData = {
id: number | null;
name: string | null;
guard_name: string | null;
group: string | null;
roles: Array<any> | null;
};
export type PickBasketData = {
id: number | null;
basket_number: string | null;
status: string | null;
items: Array<App.Data.PickBasketItemData> | null;
items_count: number | null;
created_at: string | null;
updated_at: string | null;
};
export type PickBasketItemData = {
id: number | null;
pick_basket_id: number | null;
product_id: number | null;
sku: string | null;
item_name: string | null;
qty: number | null;
warehouse_location_ids: Array<number> | null;
created_at: string | null;
updated_at: string | null;
};
export type ProductData = {
id: number | null;
sku: string | null;
name: string | null;
description: string | null;
brand: string | null;
status: string | null;
match_type: string | null;
category_id: number | null;
warehouse_position_id: number | null;
quantity: number | null;
ean: string | null;
unit: string | null;
tax: number | null;
barcode: string | null;
low_stock: number | null;
price: number | null;
max_discount: number | null;
created_at: string | null;
updated_at: string | null;
article_details: Array<any> | null;
category: Array<any> | null;
order_items: Array<App.Data.OrderItemData> | null;
cross_references: Array<App.Data.CrossReferenceData> | null;
oem_references: Array<App.Data.OemReferenceData> | null;
inventories: Array<any> | null;
file: App.Data.FileData | null;
categoryData: App.Data.CategoryData | null;
};
export type PutawayData = {
id: number | null;
asn_id: number | null;
warehouse_position_id: number | null;
putaway_by: number | null;
sku_no: string | null;
putaway_strategy: string | null;
putaway_time: string | null;
qty: number | null;
created_at: string | null;
updated_at: string | null;
asn: any | null;
putawayByUser: App.Data.UserData | null;
warehousePosition: App.Data.WarehousePositionData | null;
};
export type ReceivingSnapshotData = {
id: number | null;
quantity: number | null;
sku: string | null;
product_name: string | null;
order_number: string | null;
barcode: string | null;
product_id: number | null;
order_id: number | null;
inbound_order_item: number | null;
order_item: App.Data.OrderItemData | null;
created_at: string | null;
updated_at: string | null;
};
export type RoleData = {
id: number | null;
name: string | null;
description: string | null;
guard_name: string | null;
users_count: number | null;
permissions: Array<any> | null;
};
export type ShipOrderData = {
id: number | null;
shipment_id: string | null;
shipment_date: string | null;
total_items: number | null;
internal_order_id: number | null;
items: Array<App.Data.ShipOrderItemData> | null;
created_at: string | null;
updated_at: string | null;
};
export type ShipOrderItemData = {
id: number | null;
ship_order_id: number | null;
internal_order_item_id: number | null;
product_name: string | null;
confirmed_quantity_to_ship: number | null;
type: string | null;
customer_name: string | null;
created_at: string | null;
updated_at: string | null;
};
export type TecdocArticleData = {
id: number | null;
article_id: string | null;
article_no: string | null;
supplier_name: string | null;
article_product_name: string | null;
created_at: string | null;
updated_at: string | null;
};
export type TrackingOrderData = {
id: number | null;
order_number: string | null;
comments: string | null;
supplier: string | null;
status: string | null;
payment_status: string | null;
parcel_status: string | null;
created_by: number | null;
created_by_name: string | null;
items: Array<App.Data.TrackingOrderItemData> | null;
carriers: Array<App.Data.CarrierData> | null;
files: Array<any> | null;
created_at: string | null;
updated_at: string | null;
};
export type TrackingOrderItemData = {
id: number | null;
tracking_order_id: number | null;
item_name: string | null;
sku: string | null;
quantity: number | null;
delivered_qty: number | null;
customer_type: string | null;
customer_name: string | null;
price: number | null;
po_number: string | null;
status: string | null;
remarks: string | null;
shipped_at: string | null;
delivered_at: string | null;
created_by: number | null;
created_by_name: string | null;
created_at: string | null;
updated_at: string | null;
product: Array<any> | null;
};
export type UserData = {
role: string | null;
id: number | null;
tenant_id: number | null;
name: string | null;
phone: string | null;
email: string | null;
email_verified_at: string | null;
remember_token: string | null;
status: string | null;
created_at: string | null;
updated_at: string | null;
avatar: string | null;
roles: Array<any> | null;
permission: Array<any> | null;
files: Array<any> | null;
profile: any | null;
preferences: any | null;
notificationSettings: Array<any> | null;
lastLogin: App.Data.UserLoginLogData | null;
};
export type UserLoginLogData = {
id: number | null;
user_id: number | null;
ip_address: string | null;
device: string | null;
user_agent: string | null;
created_at: string | null;
updated_at: string | null;
user: App.Data.UserData | null;
};
export type UserNotificationSettingData = {
id: number | null;
user_id: number | null;
type: string | null;
methods: Array<any> | null;
timing: string | null;
frequency: string | null;
created_at: string | null;
updated_at: string | null;
};
export type UserPreferencesData = {
id: number | null;
user_id: number | null;
language: string | null;
timezone: string | null;
date_format: string | null;
currency: string | null;
created_at: string | null;
updated_at: string | null;
};
export type UserProfileData = {
id: number | null;
user_id: number | null;
company_name: string | null;
address: string | null;
phone_1: string | null;
phone_2: string | null;
contact_person: string | null;
company_email: string | null;
verified_at: string | null;
verified_by: string | null;
created_at: string | null;
updated_at: string | null;
};
export type WarehouseData = {
id: number | null;
merchant_id: number | null;
code: string | null;
name: string | null;
address: string | null;
city: string | null;
country: string | null;
contact_person: string | null;
contact_phone: string | null;
file: App.Data.FileData | null;
positions: Array<any> | null;
created_at: string | null;
updated_at: string | null;
};
export type WarehousePositionData = {
id: number | null;
code: string | null;
zone: string | null;
type: string | null;
capacity: number | null;
created_at: string | null;
updated_at: string | null;
putaways: Array<any> | null;
};
}
