<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .header {
            background: #f8f9fa;
            padding: 15px;
            border-left: 4px solid #007bff;
        }

        .content {
            padding: 20px 0;
        }

        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h2>New Payment Request #{{ $orderNumber }}</h2>
        </div>

        <div class="content">
            <p>Dear Accounting,</p>

            <p>Please process the attached proforma for Order <strong>#{{ $orderNumber }}</strong>, Supplier:
                <strong>{{ $supplierName }}</strong>
            </p>

            @if(!empty($userOptionalNote))
                <div style="background: #f8f9fa; padding: 15px; margin: 15px 0; border-radius: 5px;">
                    <strong>Additional Note:</strong><br>
                    {{ $userOptionalNote }}
                </div>
            @endif

            <p><strong>Request by:</strong> {{ $requestedBy }}</p>
            <p><strong>Uploaded by:</strong> {{ $uploadedBy }} on {{ $uploadDate }}</p>
            <p><strong>Click here to confirm payment:</strong>
                <a href="{{ $uploadPaymentUrl }}">{{ $uploadPaymentUrl }}</a>
            </p>


            <p>The proforma document is attached to this email.</p>
        </div>

        <div class="footer">
            <p>This email was automatically generated by the Order Tracking System.</p>
        </div>
    </div>
</body>

</html>